package framgia.co.edu.ftrr.entity;
// Generated Feb 12, 2019 2:57:27 PM by Hibernate Tools 5.1.10.Final

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import javax.persistence.*;
import java.util.Date;

/**
 * PlanResources generated by hbm2java
 */
@Entity
@Table(name = "plan_resources", catalog = "FTRR")
public class PlanResource implements java.io.Serializable {

	private Integer finalRequestId;
	private FinalResult finalResult;
	private Date date;
	private String mentor;
	private Integer traineeId;

	public PlanResource() {
	}

	public PlanResource(FinalResult finalResult) {
		this.finalResult = finalResult;
	}

	public PlanResource(FinalResult finalResult, Date date, String mentor, Integer traineeId) {
		this.finalResult = finalResult;
		this.date = date;
		this.mentor = mentor;
		this.traineeId = traineeId;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "finalResults"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "final_request_id", unique = true, nullable = false)
	public Integer getFinalRequestId() {
		return this.finalRequestId;
	}

	public void setFinalRequestId(Integer finalRequestId) {
		this.finalRequestId = finalRequestId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public FinalResult getFinalResults() {
		return this.finalResult;
	}

	public void setFinalResults(FinalResult finalResult) {
		this.finalResult = finalResult;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "mentor")
	public String getMentor() {
		return this.mentor;
	}

	public void setMentor(String mentor) {
		this.mentor = mentor;
	}

	@Column(name = "trainee_id")
	public Integer getTraineeId() {
		return this.traineeId;
	}

	public void setTraineeId(Integer traineeId) {
		this.traineeId = traineeId;
	}

}
