package framgia.co.edu.ftrr.entity;
// Generated Feb 12, 2019 2:57:27 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ResultTrainings generated by hbm2java
 */
@Entity
@Table(name = "result_trainings", catalog = "FTRR")
public class ResultTraining implements java.io.Serializable {

	private Integer id;
	private Trainee trainee;
	private User updatedBy;
	private User createdBy;
	private Integer point;
	private String content;
	private String results;
	private Date createdAt;

	public ResultTraining() {
	}

	public ResultTraining(Trainee trainee, User updatedBy, User createdBy, Integer point,
			String content, String results, Date createdAt) {
		this.trainee = trainee;
		this.updatedBy = updatedBy;
		this.createdBy = createdBy;
		this.point = point;
		this.content = content;
		this.results = results;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trainee_id")
	public Trainee getTrainees() {
		return this.trainee;
	}

	public void setTrainees(Trainee trainee) {
		this.trainee = trainee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by")
	public User getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public User getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "point")
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "results")
	public String getResults() {
		return this.results;
	}

	public void setResults(String results) {
		this.results = results;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
