package framgia.co.edu.ftrr.entity;
// Generated Feb 12, 2019 2:57:27 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.*;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ResultTypes generated by hbm2java
 */
@Entity
@Table(name = "result_types", catalog = "FTRR")
public class ResultType implements java.io.Serializable {

	private Integer id;
	private String name;
	private List<ResultInterview> resultInterviewses;

	public ResultType() {
	}

	public ResultType(String name, List<ResultInterview> resultInterviewses) {
		this.name = name;
		this.resultInterviewses = resultInterviewses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resultTypes")
	public List<ResultInterview> getResultInterviewses() {
		return this.resultInterviewses;
	}

	public void setResultInterviewses(List<ResultInterview> resultInterviewses) {
		this.resultInterviewses = resultInterviewses;
	}

}
